### ISSUE TITLE
about the algorithm you mention

### ISSUE THREAD

**Issue by xuchen-dev** [EvoCargo/RaindropsOnWindshield#1]
could you provide the code about the algorithm you mention  
and  how  can i run the code you provide  make my our img with raindrop

**Comment by oleg-Shipitko** [comment]
Hello!
The code to generate raindrops is provided in repo. See link below for Jupyter notebook with usage example:
https://github.com/EvoCargo/RaindropsOnWindshield/blob/main/raindrops_generator/Main.ipynb
